### ISSUE TITLE
Simple GUIDE

### ISSUE THREAD

**Issue by lars18th** [whizzzkid/github-sync-fork-chrome-ext#1]
Please, can you provide a simple guide?
I installed the extension, but I don't know how to use it.

Thank you!

**Comment by whizzzkid** [comment]
There you go: https://github.com/whizzzkid/github-sync-fork-chrome-ext/wiki/How-To-Use

**Comment by lars18th** [comment]
Hi @whizzzkid ,

Thank you for the Wiki!

However, when I go to the page of my fork (or any of my forks), I never see the button **"Sync Fork"**. The extension is installed in Chrome (Windows 64bit) and active.
I need to do something more?

**NOTE:** After more testing I see that _in some of my forks_ I can see the button, but not on others. What's the difference?

Regards.

**Comment by whizzzkid** [comment]
The button only appears if there is anything available for sync.

**Comment by lars18th** [comment]
OK. Thank you!

I suggest to write the link of the Wiki inside the Chrome Web Store and in the README.me of the GitHub repository. This will help to other new users.

You agree?

**Comment by whizzzkid** [comment]
Thanks for the update, done and done!
