### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by peterennis** [whizzzkid/github-sync-fork-chrome-ext#2]
Click on GitHub Synch Fork in Chrome and it wants to install
the extension that is already installed.
Loop. . .

![capture247](https://user-images.githubusercontent.com/140737/37246182-6063a886-2459-11e8-8787-29ead62b9b94.png)

![capture248](https://user-images.githubusercontent.com/140737/37246184-657433ea-2459-11e8-8a16-558f9fc63797.png)

**Comment by whizzzkid** [comment]
Did you read the wiki? https://github.com/whizzzkid/github-sync-fork-chrome-ext/wiki/How-To-Use

Chrome generates icons for all extensions even if no browser actions are defined, there is nothing to be done there. It will add a button to your fork to sync it.

**Comment by peterennis** [comment]
It works.
Some notes that could be added to the docs:

1. The Synch button looks like this:
![capture249](https://user-images.githubusercontent.com/140737/37382408-f91772b2-26ff-11e8-9300-4550e050f1c4.png)

2. The synch button only appears when there are commits ahead of the fork.

Looking good so far!

**Comment by peterennis** [comment]
Closed as working!
